name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        - name: Validate Render Deploy Hook
        run: echo "RENDER_DEPLOY_HOOK is ${{ secrets.RENDER_DEPLOY_HOOK }}"
        shell: bash

      - name: Trigger Render Deploy Hook
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}